version: '2'

networks:
    stack:
        driver: bridge

services:
    nginx:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www
            - ./log:/var/log/nginx
        networks:
            - stack

    php:
        image: php:fpm
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - ./conf/php.conf:/usr/local/etc/php-fpm.d/zz-php.conf
            - ./src:/var/www
        networks:
            - stack

    mysql:
        image: mysql
        ports:
            - 3300:3306
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: www
            MYSQL_PASSWORD: www
            MYSQL_DATABASE: www
        networks:
            - stack
